### ISSUE TITLE
redirects: add redirect for gonum/exp

### ISSUE THREAD

**Issue by kortschak** [gonum/gonum.github.io#8]

**Comment by sbinet** [comment]
is this the right place to add the `gonum.org/v1/exp/...` redirect? or is it over [gonum/website](https://github.com/gonum/website)?

I am a bit confused...

**Comment by btracey** [comment]
gonum/website is the real one.

**Comment by sbinet** [comment]
closing (in favour of https://github.com/gonum/website/issues/20)
